application: een-track
version: app-viper-1
runtime: python27
api_version: 1
threadsafe: true

derived_file_type:
- python_precompiled

libraries:
- name: django
  version: "1.2"

handlers:
- url: /images
  static_dir: templates/_images

- url: /css
  static_dir: templates/_css

- url: /js
  static_dir: templates/_js

- url: /favicon.ico
  static_files: templates/_images/favicon.ico
  upload: templates/_images/favicon.ico

- url: /robots.txt
  static_files: templates/_images/robots.txt
  upload: templates/_images/favicon.ico

- url: /t
  static_files: templates/_js/jquery.tracker.js
  upload: templates/_images/favicon.ico
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /.*
  script: main.app
